import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "KEY NAME", uid: "keyname", sortable: true},
  {name: "KEY VALUE", uid: "keyvalue", sortable: true},
  {name: "INITIALDATE", uid: "initialdate", sortable: true},
  {name: "EXPIRATIONDATE", uid: "expirationdate"},
  {name: "DESCRIPTION", uid: "description"},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Vacation", uid: "vacation"},
];

const users = [
  {
    id: 1,
    keyname: "GoldKey",
    keyvalue: "2B5E9F4D",
    initialdate: "2023-01-15",
    expirationdate: "2024-12-31",
    description: "Experienced manager with strategic vision.",
  },
  {
    id: 2,
    keyname: "SilverKey",
    keyvalue: "1C5D3A8B",
    initialdate: "2023-02-20",
    expirationdate: "2024-11-30",
    description: "Skilled tech lead specializing in backend development.",
  },
  {
    id: 3,
    keyname: "BronzeKey",
    keyvalue: "7E2F4A1C",
    initialdate: "2023-03-10",
    expirationdate: "2024-10-31",
    description: "Young developer with a passion for coding.",
  },
  {
    id: 4,
    keyname: "MasterKey",
    keyvalue: "9D5A8B2E",
    initialdate: "2023-04-05",
    expirationdate: "2024-09-30",
    description: "Creative marketer with a focus on digital campaigns.",
  },
  {
    id: 5,
    keyname: "SkeletonKey",
    keyvalue: "6B8D1F4C",
    initialdate: "2023-05-12",
    expirationdate: "2024-08-31",
    description: "Dynamic salesperson known for closing deals effectively.",
  },
  {
    id: 6,
    keyname: "DigitalKey",
    keyvalue: "3F6C9E5B",
    initialdate: "2023-06-18",
    description: "Innovative manager driving digital transformation.",
    expirationdate: "2024-07-31",
  },
  {
    id: 7,
    keyname: "SmartKey",
    keyvalue: "4B7E1D3A",
    initialdate: "2023-07-22",
    expirationdate: "2024-06-30",
    description: "Creative designer with a flair for user-centric design.",
  },
  {
    id: 8,
    keyname: "KeyFob",
    keyvalue: "5D2A7C1E",
    initialdate: "2023-08-14",
    expirationdate: "2024-05-31",
    description: "Efficient HR manager skilled in team building.",
  },
  {
    id: 9,
    keyname: "LockKey",
    keyvalue: "3B8F4A2D",
    initialdate: "2023-09-30",
    expirationdate: "2024-04-30",
    description: "Detail-oriented finance manager with strong analytical skills.",
  },
  {
    id: 10,
    keyname: "RemoteKey",
    keyvalue: "7E3C1B8D",
    initialdate: "2023-10-19",
    expirationdate: "2024-03-31",
    description: "Operations manager driving efficiency and process improvement.",
  },
  {
    id: 11,
    keyname: "Keyring",
    keyvalue: "6E9F5A7C",
    initialdate: "2023-11-25",
    expirationdate: "2024-02-29",
    description: "Passionate developer eager to learn and grow.",
  },
  {
    id: 12,
    keyname: "KeyPad",
    keyvalue: "2B8D1A5C",
    initialdate: "2023-12-08",
    expirationdate: "2024-01-31",
    description: "Product manager specializing in product lifecycle management.",
  },
  {
    id: 13,
    keyname: "KeyChain",
    keyvalue: "9F4B8E3C",
    initialdate: "2024-01-14",
    expirationdate: "2023-12-31",
    description: "Security expert skilled in cybersecurity and risk management.",
  },
  {
    id: 14,
    keyname: "AccessKey",
    keyvalue: "4A2D7C5E",
    initialdate: "2024-02-21",
    expirationdate: "2023-11-30",
    description: "Marketing specialist with expertise in digital marketing strategies.",
  },
  {
    id: 15,
    keyname: "SecureKey",
    keyvalue: "3A8C1D4E",
    initialdate: "2024-03-05",
    expirationdate: "2023-10-31",
    description: "IT specialist proficient in managing complex IT systems.",
  },
  {
    id: 16,
    keyname: "TokenKey",
    keyvalue: "1B8D5F9E",
    initialdate: "2024-04-19",
    expirationdate: "2023-09-30",
    description: "Sales expert with a knack for customer relationship management.",
  },
  {
    id: 17,
    keyname: "PassKey",
    keyvalue: "8F4B9E2A",
    initialdate: "2024-05-30",
    expirationdate: "2023-08-31",
    description: "Data analyst skilled in statistical analysis and data visualization.",
  },
  {
    id: 18,
    keyname: "KeyCard",
    keyvalue: "7D2A8C4E",
    initialdate: "2024-06-15",
    expirationdate: "2023-07-31",
    description: "QA analyst ensuring software quality through rigorous testing.",
  },
  {
    id: 19,
    keyname: "DigitalLock",
    keyvalue: "2B7E5F9D",
    initialdate: "2024-07-25",
    expirationdate: "2023-06-30",
    description: "IT administrator managing complex IT infrastructures.",
  },
  {
    id: 20,
    keyname: "SecureAccess",
    keyvalue: "7E3C9B4D",
    initialdate: "2024-08-12",
    expirationdate: "2023-05-31",
    description: "Operations coordinator ensuring smooth workflow and efficiency.",
  },
];


export {columns, users, statusOptions};
